repos:
  - repo: local
    hooks:
      - id: handsdown
        name: handsdown
        entry: handsdown
        language: system
        types: [python]
        require_serial: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.393
    hooks:
    - id: pyright