name: docker-build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
env:
  REGISTRY: ghcr.io
jobs:
  build:
    if: ${{ contains(fromJson('["main"]'), github.ref_name) || github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag
        id: semver_tag
        run: |
          GIT_TAG=${{ github.ref_name  }}
          echo "TAG=${GIT_TAG#*v}" >> $GITHUB_OUTPUT

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/memer
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.semver_tag.outputs.TAG }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}